version: '3.8'

services:
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - patient-management-network

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "8001:8001"
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - patient-management-network

networks:
  patient-management-network:
    driver: bridge