#Create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
"name" :"Virtue Aina",
"email":"VAA@egmail.com",
"address":"18, Victoria Ave",
  "dateOfBirth": "1995-09-09",
"registeredDate":"2024-11-28"
}